### ISSUE TITLE
Consider renaming examples/go

### ISSUE THREAD

**Issue by mewmew** [Telroshan/go-sfml#1]
Running `go get -u gopkg.in/teh-cmc/go-sfml.v24/...` compiles and installs the `go` example into $GOPATH/bin. For users with $GOPATH/bin in their $PATH, the `go` example program may gain precedence over the `go` tool of the Go distribution.

**Comment by teh-cmc** [comment]
Ooh, that's a new kind of nasty 😄 

I'll fix that right now, thanks!

**Comment by mewmew** [comment]
Thanks for the quick response :)
